version: '3.8'
services:
  postgres:
    image: postgres:14
    container_name: local_pg
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=udemy-clone
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - '5452:5432'
volumes:
  pgdata: